# Name: Gayatri Bhosale
### PRN: 25070123033
## Experiment 9: Study Of Pandas Library

In [1]:
#Pandas
'''structured data
EDA
Data Cleaning'''

'structured data \nEDA\nData Cleaning'

In [42]:
import pandas as pd
s= pd.Series([10,20,30,40])
s

0    10
1    20
2    30
3    40
dtype: int64

In [43]:
#Create DataFrame
data={
    "Name":["A","B","C"],
    "Marks":[90,95,100]
}
df = pd.DataFrame(data)
df

  Name  Marks
0    A     90
1    B     95
2    C    100

In [44]:
#find the structure of the dataframe
df.shape

(3, 2)

In [45]:
df.ndim

2

In [46]:
df.size

6

In [47]:
#Display Column Names
df.columns

Index(['Name', 'Marks'], dtype='object')

In [48]:
#Check Data Types Of Each Column
df.dtypes

Name     object
Marks     int64
dtype: object

In [49]:
#Access Individual Column
df["Name"]

0    A
1    B
2    C
Name: Name, dtype: object

In [50]:
df["Marks"]

0     90
1     95
2    100
Name: Marks, dtype: int64

In [51]:
#Access Specific Row
df.loc[1]

Name      B
Marks    95
Name: 1, dtype: object

In [60]:
#Add a New Column
df["Grade"]=["Second Class","First Class","Distinction"]
df

  Name  Marks         Grade
0    A     88  Second Class
1    B     95   First Class
2    C    100   Distinction

In [61]:
#Update Data In DataFrame
#Change marks Of Students A to 88.
df.loc[0,"Marks"]= 88
df

  Name  Marks         Grade
0    A     88  Second Class
1    B     95   First Class
2    C    100   Distinction

In [62]:
#Delet A Column
df.drop("Grade",axis=1 ,inplace=True)
df

  Name  Marks
0    A     88
1    B     95
2    C    100

In [63]:
#Perform Basic Statistcal Analysis
mean1 = df["Marks"].mean()
mean1

np.float64(94.33333333333333)

In [64]:
min1=df["Marks"].min()
min1

88

In [67]:
max1=df["Marks"].max()
max1

100

In [68]:
#Apply Condition (Filtering)
#Display students scoring more than 80

df[df["Marks"]>80]

  Name  Marks
0    A     88
1    B     95
2    C    100